name: "Push Notify on Whatsapp chat"
description: "Triggers a Private Message to the specified Whatsapp user when code is pushed in the master branch"
author: "Atif Azeez"
branding:
  icon: message-square
  color: blue


runs:
  using: "docker"
  image: "Dockerfile"
